name: "UbuntuBuild"

on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build for Ubuntu
    runs-on: ubuntu-latest
    permissions: write-all

    strategy:
      fail-fast: false
  
    steps:
    - name: Install dependencies
      run: sudo apt update 
        && sudo apt install -y protobuf-c-compiler libprotobuf-c-dev
        
    - name: Install Libfabric
      run: git clone https://github.com/ofiwg/libfabric.git
        && cd ./libfabric
        && sudo ./autogen.sh
        && ./configure --prefix=/opt/libfabric
            --enable-only
            --enable-tcp=yes
            --enable-rxm=yes
        && make -j $(nproc)
        && sudo make install
        && sudo cp -r include/. /usr/include

    - name: Cleanup
      run: sudo chown -R $USER:$USER $(pwd)
        && sudo rm -rf $(pwd)/libfabric

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build
      run: cd libtrf
        && cmake .
        && make -j $(nproc)
